name: Docker Build

on:
  workflow_call:
    inputs:
      image_name:
        description: Name of the final Docker image, not including the registry or tag
        type: string
        required: true
      tag_rules:
        description: Rules to be used to determine the tag for the Docker image. See the readme for https://github.com/docker/metadata-action for more information.
        type: string
        default: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value={{branch}}-{{sha}}-{{date 'YYYYMMDD-HHmmss' tz='America/St_Johns'}},enable={{is_default_branch}}
      dockerfile_path:
        description: Path to the Dockerfile to build.
        type: string
        default: Dockerfile

permissions: {}

jobs:
  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      attestations: write # Needed to create attestations
      contents: read # Needed to clone the repository
      id-token: write # Needed to sign attestations
      packages: write # Needed to push to GitHub Container Registry

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
        with:
          cache-binary: false

      - name: Login to target registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          # TODO: Support other registries
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate image metadata
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        id: metadata
        with:
          images: ghcr.io/${{ inputs.image_name }}
          tags: ${{ inputs.tag_rules }}

      - name: Build and push Docker image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        id: push
        with:
          context: .
          file: "${{ inputs.dockerfile_path }}"
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
        with:
          subject-name: ghcr.io/${{ inputs.image_name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
