name: Earthly Build

on:
  workflow_call:
    inputs:
      target:
        description: The target to build in the Earthfile
        type: string
        default: +app

permissions: {}

jobs:
  earthly-build:
    name: Build Docker image with Earthly
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to clone the repository
      packages: write # Needed to push to GitHub Container Registry

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Earthly
        uses: earthly/actions-setup@43211c7a0eae5344d6d79fb4aaf209c8f8866203 # v1.0.13
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to target registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          # TODO: Support other registries
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate sortable image tag
        id: image_tag
        run: |
          BRANCH="${{ github.ref_name }}"
          SHORT_SHA="${{ github.sha }}"
          SHORT_SHA="${SHORT_SHA:0:7}"
          TIMESTAMP=$(TZ="America/St_Johns" date +"%Y%m%d-%H%M%S")
          TAG="${BRANCH}-${SHORT_SHA}-${TIMESTAMP}"
          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"

      - name: Build & push with Earthly
        run: earthly --ci --push "$TARGET" --TAG="${{ steps.image_tag.outputs.tag }}"
        env:
          TARGET: ${{ inputs.target }}
