name: golangci-lint

on:
  workflow_call:

permissions: {}

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    permissions:
      checks: write # Needed to post check run results
      contents: read # Needed to clone the repository
      pull-requests: read # Needed to read PR information
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version: latest
          only-new-issues: true
